"""added softdelete to zones table

Revision ID: 03352c8e289c
Revises: 230f54269726
Create Date: 2024-10-22 10:56:48.336759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03352c8e289c'
down_revision = '230f54269726'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zones', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###
