"""empty message

Revision ID: 04df34d2064f
Revises: 34377cb39e25
Create Date: 2024-10-29 06:29:59.462424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04df34d2064f'
down_revision = '34377cb39e25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)

    # ### end Alembic commands ###
