"""created cameras table with soft delete

Revision ID: 15bdded73764
Revises: ff534d1e4167
Create Date: 2024-08-07 11:51:39.444106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15bdded73764'
down_revision = 'ff534d1e4167'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cameras',
    sa.Column('user_id', sa.String(length=225), nullable=False),
    sa.Column('camera_name', sa.String(length=150), nullable=False),
    sa.Column('camera_ip', sa.Integer(), nullable=False),
    sa.Column('cameera_type', sa.String(length=150), nullable=False),
    sa.Column('camera_zone', sa.String(length=150), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('camera_ip'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    op.drop_table('cameras')
    # ### end Alembic commands ###
