"""basic changes in database

Revision ID: 165e5c9bd01b
Revises: ccc09511fe69
Create Date: 2024-08-10 14:57:24.816290

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '165e5c9bd01b'
down_revision = 'ccc09511fe69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.alter_column('deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['camera_id'])
        batch_op.drop_constraint('cameras_camera_zone_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'zones', ['camera_zone'], ['zone_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('cameras_camera_zone_fkey', 'zones', ['camera_zone'], ['zone_name'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    # ### end Alembic commands ###
