"""fixed column typo

Revision ID: 21db61e985f7
Revises: 3d012d756725
Create Date: 2024-08-10 15:44:43.205126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21db61e985f7'
down_revision = '3d012d756725'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.add_column(sa.Column('camera_type', sa.String(length=150), nullable=False))
        batch_op.drop_column('cameera_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cameera_type', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
        batch_op.drop_column('camera_type')

    # ### end Alembic commands ###
