"""adding zone table 

Revision ID: 230f54269726
Revises: 
Create Date: 2024-10-22 10:54:04.592100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '230f54269726'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zones', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['zone_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zones', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
