"""chamged the nullable value for email 

Revision ID: 34377cb39e25
Revises: 8d206f045364
Create Date: 2024-10-29 06:28:02.889990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34377cb39e25'
down_revision = '8d206f045364'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)

    # ### end Alembic commands ###
