"""added camera_username colimn to camera table

Revision ID: 3d012d756725
Revises: 165e5c9bd01b
Create Date: 2024-08-10 15:23:16.930382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d012d756725'
down_revision = '165e5c9bd01b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.add_column(sa.Column('camera_username', sa.String(length=150), nullable=False))
        batch_op.create_unique_constraint(None, ['camera_username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('camera_username')

    # ### end Alembic commands ###
