"""new tabels

Revision ID: 4aad4a6fba09
Revises: a6bece857444
Create Date: 2024-09-11 12:00:27.136138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aad4a6fba09'
down_revision = 'a6bece857444'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.String(length=225), nullable=False),
    sa.Column('name', sa.String(length=225), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('accesses',
    sa.Column('id', sa.String(length=225), nullable=False),
    sa.Column('permissions_id', sa.String(length=225), nullable=True),
    sa.ForeignKeyConstraint(['permissions_id'], ['permissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('user_accesses',
    sa.Column('id', sa.String(length=225), nullable=False),
    sa.Column('user_id', sa.String(length=225), nullable=True),
    sa.Column('access_id', sa.String(length=225), nullable=True),
    sa.ForeignKeyConstraint(['access_id'], ['accesses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_accesses')
    op.drop_table('accesses')
    op.drop_table('permissions')
    # ### end Alembic commands ###
