"""changed some columns

Revision ID: 4fe477f57053
Revises: cb7f365f1da8
Create Date: 2024-08-10 17:24:22.459669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fe477f57053'
down_revision = 'cb7f365f1da8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.drop_constraint('cameras_camera_zone_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'zones', ['camera_zone'], ['zone_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('cameras_camera_zone_fkey', 'zones', ['camera_zone'], ['zone_id'])

    # ### end Alembic commands ###
