"""modified camera_password 

Revision ID: 53df7f999586
Revises: 7033744a90ba
Create Date: 2024-08-20 10:21:06.086296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53df7f999586'
down_revision = '7033744a90ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.add_column(sa.Column('camera_password', sa.String(length=150), nullable=False))
        batch_op.drop_column('camera_password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.add_column(sa.Column('camera_password_hash', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
        batch_op.drop_column('camera_password')

    # ### end Alembic commands ###
