"""empty message

Revision ID: 5646da2cba03
Revises: a2d64825058b
Create Date: 2024-09-17 12:23:39.260891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5646da2cba03'
down_revision = 'a2d64825058b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accesses', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['module_id'])

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('user_accesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['id'])
        batch_op.create_foreign_key(None, 'accesses', ['access_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_accesses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('access_id')

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('accesses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
