"""added camera_record to camera table

Revision ID: 593af599366d
Revises: 
Create Date: 2024-08-28 15:56:28.648748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '593af599366d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.add_column(sa.Column('camera__record', sa.Boolean(), nullable=True))
        batch_op.drop_column('camera_recording')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.add_column(sa.Column('camera_recording', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('camera__record')

    # ### end Alembic commands ###
