"""added ai_properties table

Revision ID: 595ac068d481
Revises: 
Create Date: 2024-09-01 16:55:06.339880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '595ac068d481'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_properties',
    sa.Column('id', sa.String(length=225), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('label', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_property_id', sa.String(length=250), nullable=True))
        batch_op.create_foreign_key(None, 'ai_properties', ['ai_property_id'], ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('ai_property_id')

    op.drop_table('ai_properties')
    # ### end Alembic commands ###
