"""added models for user management

Revision ID: 6334054fba19
Revises: a7aea57643d2
Create Date: 2024-09-11 10:29:58.153822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6334054fba19'
down_revision = 'a7aea57643d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_access',
    sa.Column('user_id', sa.String(length=225), nullable=True),
    sa.Column('camera_id', sa.String(length=225), nullable=True),
    sa.Column('permission_id', sa.String(length=225), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.camera_id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], )
    )
    with op.batch_alter_table('accesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('camera_id', sa.String(length=225), nullable=True))
        batch_op.create_unique_constraint(None, ['id'])
        batch_op.drop_constraint('accesses_module_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'cameras', ['camera_id'], ['camera_id'])
        batch_op.drop_column('module_id')

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('accesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('module_id', sa.VARCHAR(length=225), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('accesses_module_id_fkey', 'cameras', ['module_id'], ['camera_id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('camera_id')

    op.drop_table('user_access')
    # ### end Alembic commands ###
