"""added user access to cameras and zones

Revision ID: 6c0817abd9ff
Revises: 3353ee037441
Create Date: 2024-11-27 19:55:34.297790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c0817abd9ff'
down_revision = '3353ee037441'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zone_accesses')
    op.drop_table('camera_accesses')
    with op.batch_alter_table('accesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('camera_id', sa.String(length=225), nullable=True))
        batch_op.add_column(sa.Column('zone_id', sa.String(length=225), nullable=True))
        batch_op.alter_column('module_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'zones', ['zone_id'], ['zone_id'])
        batch_op.create_foreign_key(None, 'cameras', ['camera_id'], ['camera_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accesses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('module_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('zone_id')
        batch_op.drop_column('camera_id')

    op.create_table('camera_accesses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=225), autoincrement=False, nullable=False),
    sa.Column('camera_id', sa.VARCHAR(length=225), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.camera_id'], name='camera_accesses_camera_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='camera_accesses_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='camera_accesses_pkey'),
    sa.UniqueConstraint('id', name='camera_accesses_id_key')
    )
    op.create_table('zone_accesses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=225), autoincrement=False, nullable=False),
    sa.Column('zone_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='zone_accesses_user_id_fkey'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.zone_id'], name='zone_accesses_zone_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='zone_accesses_pkey')
    )
    # ### end Alembic commands ###
