"""added image column to camera table

Revision ID: 7033744a90ba
Revises: 4fe477f57053
Create Date: 2024-08-12 14:20:27.060141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7033744a90ba'
down_revision = '4fe477f57053'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.add_column(sa.Column('camera_image_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.drop_column('camera_image_path')

    # ### end Alembic commands ###
