"""fixed camera record feald

Revision ID: 7d671916f64d
Revises: 595ac068d481
Create Date: 2024-09-03 09:45:14.035531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d671916f64d'
down_revision = '595ac068d481'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_properties', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.add_column(sa.Column('camera_record', sa.Boolean(), nullable=True))
        batch_op.drop_column('camera__record')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.add_column(sa.Column('camera__record', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('camera_record')

    with op.batch_alter_table('ai_properties', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
