"""Fixed name column uniquenes

Revision ID: 809c976a96dc
Revises: ee9dc4841829
Create Date: 2024-09-03 11:10:30.731612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '809c976a96dc'
down_revision = 'ee9dc4841829'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_properties', schema=None) as batch_op:
        batch_op.drop_constraint('ai_properties_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_properties', schema=None) as batch_op:
        batch_op.create_unique_constraint('ai_properties_name_key', ['name'])

    # ### end Alembic commands ###
