"""added label to modules table

Revision ID: 8575e6e3fa92
Revises: 5646da2cba03
Create Date: 2024-09-17 16:44:26.057611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8575e6e3fa92'
down_revision = '5646da2cba03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label', sa.String(length=225), nullable=True))
        batch_op.create_unique_constraint(None, ['label'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('label')

    # ### end Alembic commands ###
