"""added label column to permissions table

Revision ID: 8c029d0dbb75
Revises: 8575e6e3fa92
Create Date: 2024-09-17 16:47:56.150336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c029d0dbb75'
down_revision = '8575e6e3fa92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.drop_constraint('modules_label_key', type_='unique')
        batch_op.drop_column('label')

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label', sa.String(length=225), nullable=True))
        batch_op.create_unique_constraint(None, ['label'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('label')

    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label', sa.VARCHAR(length=225), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('modules_label_key', ['label'])

    # ### end Alembic commands ###
