"""added one to many relationship to camera table 

Revision ID: 902435eb34f4
Revises: 7d671916f64d
Create Date: 2024-09-03 10:05:52.626889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '902435eb34f4'
down_revision = '7d671916f64d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('camera_id', sa.String(), nullable=True))
        batch_op.create_foreign_key(None, 'cameras', ['camera_id'], ['camera_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_properties', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('camera_id')

    # ### end Alembic commands ###
