"""added module tabel

Revision ID: a6bece857444
Revises: 60f4e1e82e8b
Create Date: 2024-09-11 11:43:32.688733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6bece857444'
down_revision = '60f4e1e82e8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accesses')
    op.drop_table('permissions')
    op.drop_table('user_access')
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['module_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.create_table('user_access',
    sa.Column('user_id', sa.VARCHAR(length=225), autoincrement=False, nullable=True),
    sa.Column('access_id', sa.VARCHAR(length=225), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['access_id'], ['accesses.id'], name='user_access_access_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='user_access_user_id_fkey')
    )
    op.create_table('permissions',
    sa.Column('id', sa.VARCHAR(length=225), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=225), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='permissions_pkey'),
    sa.UniqueConstraint('id', name='permissions_id_key'),
    sa.UniqueConstraint('name', name='permissions_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('accesses',
    sa.Column('id', sa.VARCHAR(length=225), autoincrement=False, nullable=False),
    sa.Column('permissions_id', sa.VARCHAR(length=225), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['permissions_id'], ['permissions.id'], name='accesses_permissions_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='accesses_pkey'),
    sa.UniqueConstraint('id', name='accesses_id_key')
    )
    # ### end Alembic commands ###
