"""removed the changes

Revision ID: a7aea57643d2
Revises: 802eb1a3ce5a
Create Date: 2024-09-11 10:21:10.153194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7aea57643d2'
down_revision = '802eb1a3ce5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_access')
    op.drop_table('accesses')
    op.drop_table('permissions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=225), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='permissions_pkey'),
    sa.UniqueConstraint('id', name='permissions_id_key'),
    sa.UniqueConstraint('name', name='permissions_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('accesses',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('module_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('permisions_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['cameras.camera_id'], name='accesses_module_id_fkey'),
    sa.ForeignKeyConstraint(['permisions_id'], ['permissions.id'], name='accesses_permisions_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='accesses_pkey'),
    sa.UniqueConstraint('id', name='accesses_id_key')
    )
    op.create_table('user_access',
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('camera_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('permission_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.camera_id'], name='user_access_camera_id_fkey'),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name='user_access_permission_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='user_access_user_id_fkey')
    )
    # ### end Alembic commands ###
