"""added cameras table 

Revision ID: be34295e25e2
Revises: 03352c8e289c
Create Date: 2024-10-22 10:59:14.690798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be34295e25e2'
down_revision = '03352c8e289c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['camera_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
