"""up to data

Revision ID: cb7f365f1da8
Revises: 21db61e985f7
Create Date: 2024-08-10 17:07:31.779212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb7f365f1da8'
down_revision = '21db61e985f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.drop_constraint('cameras_camera_username_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.create_unique_constraint('cameras_camera_username_key', ['camera_username'])

    # ### end Alembic commands ###
