"""changed zone xolumn name

Revision ID: ccc09511fe69
Revises: ef329dcbd259
Create Date: 2024-08-10 13:19:29.501160

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ccc09511fe69'
down_revision = 'ef329dcbd259'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cameras')
    with op.batch_alter_table('zones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zone_name', sa.String(length=225), nullable=False))
        batch_op.add_column(sa.Column('zone_desc', sa.Text(), nullable=True))
        batch_op.drop_constraint('zones_name_key', type_='unique')
        batch_op.create_unique_constraint(None, ['zone_name'])
        batch_op.drop_column('name')
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=225), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('zones_name_key', ['name'])
        batch_op.drop_column('zone_desc')
        batch_op.drop_column('zone_name')

    op.create_table('cameras',
    sa.Column('camera_id', sa.VARCHAR(length=225), autoincrement=False, nullable=False),
    sa.Column('camera_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('camera_ip', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('cameera_type', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('camera_zone', sa.VARCHAR(length=225), autoincrement=False, nullable=False),
    sa.Column('camera_password_hash', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['camera_zone'], ['zones.name'], name='cameras_camera_zone_fkey'),
    sa.PrimaryKeyConstraint('camera_id', name='cameras_pkey'),
    sa.UniqueConstraint('camera_ip', name='cameras_camera_ip_key')
    )
    # ### end Alembic commands ###
