"""empty message

Revision ID: cdda0c53641d
Revises: 8c029d0dbb75
Create Date: 2024-09-17 16:50:35.912325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdda0c53641d'
down_revision = '8c029d0dbb75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_constraint('permissions_label_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_unique_constraint('permissions_label_key', ['label'])

    # ### end Alembic commands ###
