"""Fix camera and AI properties models

Revision ID: ee9dc4841829
Revises: 902435eb34f4
Create Date: 2024-09-03 11:06:28.801967

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ee9dc4841829'
down_revision = '902435eb34f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camera_ai_relationship',
    sa.Column('camera_id', sa.String(length=225), nullable=False),
    sa.Column('ai_property_id', sa.String(length=225), nullable=False),
    sa.ForeignKeyConstraint(['ai_property_id'], ['ai_properties.id'], ),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.camera_id'], ),
    sa.PrimaryKeyConstraint('camera_id', 'ai_property_id')
    )
    with op.batch_alter_table('ai_properties', schema=None) as batch_op:
        batch_op.drop_constraint('ai_properties_camera_id_fkey', type_='foreignkey')
        batch_op.drop_column('camera_id')

    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.drop_constraint('cameras_ai_property_id_fkey', type_='foreignkey')
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('ai_property_id')
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ai_property_id', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('cameras_ai_property_id_fkey', 'ai_properties', ['ai_property_id'], ['name'])

    with op.batch_alter_table('ai_properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('camera_id', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('ai_properties_camera_id_fkey', 'cameras', ['camera_id'], ['camera_id'])

    op.drop_table('camera_ai_relationship')
    # ### end Alembic commands ###
